// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAdbDevices() {
  return window['go']['main']['App']['GetAdbDevices']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}
