// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAdbDevices():Promise<Array<main.Device>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileItem>>;
