// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureScreen(arg1:string,arg2:string):Promise<void>;

export function ConnectWifi(arg1:string):Promise<string>;

export function DownloadFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function GetAdbDevices():Promise<Array<main.Device>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileItem>>;

export function RecordScreen(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StopScreenRecord(arg1:string):Promise<void>;
