// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1, arg2) {
  return window['go']['main']['App']['CaptureScreen'](arg1, arg2);
}

export function DownloadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFiles'](arg1, arg2, arg3);
}

export function GetAdbDevices() {
  return window['go']['main']['App']['GetAdbDevices']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function RecordScreen(arg1, arg2) {
  return window['go']['main']['App']['RecordScreen'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StopScreenRecord(arg1) {
  return window['go']['main']['App']['StopScreenRecord'](arg1);
}
